# Main Menu
BUY = "BUY"
SELL = "SELL"
MY_ORDERS = "MY_ORDERS"
BACK_MAIN = "BACK_MAIN"

# Order Flow
BUY_SLOT_PREFIX = "BUY_SLOT_"
SELL_SLOT_PREFIX = "SELL_SLOT_"

QTY_PREFIX = "QTY_"

CONFIRM_ORDER = "CONFIRM_ORDER"
CANCEL_ORDER = "CANCEL_ORDER"